name: Build, Test and Deploy

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: ["main"]
    paths:
      - "src/**"

  workflow_dispatch:

jobs:
  build_test:
    name: Build and Test
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven         

      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml